### ISSUE TITLE
design CTS256 alternative

### ISSUE THREAD

**Issue by lynchaj** [jim11662418/CTS256-SP0256#1]
Hi
I've had an idea of how to replace the hard to get and expensive CTS256 with a much less expensive alternative using similar, comparable parts (no exotic FPGAs, controllers, etc.) I would like to contact you but have no email for you and cannot find a way to direct message you on GitHub. Would you please contact me on GitHub or send me an email at

L Y N C H A J .at. Y A H O O .dot. C O M

Or you can reach me on retro-comp mailing list, retrobrewcomputers.org forum, or retrocomputingforum.com

Thank you! Andrew Lynch

**Comment by jim11662418** [comment]
Greetings,
You can reach me at: ***@***.***

**Comment by lynchaj** [comment]
Hi JimThanks!
It looks like GitHub censored your email address.  Would you please send an email direct to my yahoo account?
Sorry for posting the issue.  I wish GitHub had a way to direct message other registered users.
Thanks!  Andrew Lynch
 
    On Friday, March 29, 2024 at 06:18:46 AM EDT, Jim ***@***.***> wrote:  
 
 

Greetings,
You can reach me at: ***@***.***

**Comment by jim11662418** [comment]
j_i_m_1_1_6_6_2_4_1_8 at g_m_a_i_l dot c_o_m
